[package]
name = "stc-bridge-move"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
Bridge = "0x246b237c16c761e9478783dd83f7004a"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "4328795207baa1fd580755c4d1948c916024e290" }